[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.15.0", features = ["ndarray"] }
itertools = "0.13.0"
ndarray = "0.16.1"
nom = "7.1.3"
